### ISSUE TITLE
upload artifacts from "Build assets" step in build.yml

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/cookiecutter-adafruit-circuitpython#92]
It just occurred to me that I could use the build.yml workflow to generate my mpy files for testing (or verifying the assets are correct before release). I'm noting it here as it might be very useful to people developing from windows (without WSL setup) or from lower-end dev stations (like tablets or a [GitPod env](https://www.gitpod.io/)).

I was able to get this done by adding 
```yml
    - name: Archive bundles
      uses: actions/upload-artifact@v2
      with:
        name: bundles
        path: ${{ github.workspace }}/bundles/
```
directly after the "Build assets" step which resulted with
![image](https://user-images.githubusercontent.com/14963867/101663180-3a26d800-39ff-11eb-8dff-5ae7213bd11e.png)
I can easily submit a PR if this is an acceptable contribution
